<?php
$lang_text      = array(
    '500_desc' => '數據庫錯誤.',
    '500_title' => '該頁面不是.',
    '404_desc' => '該頁面不是.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => '錯誤!',
    'Error_2' => '信息無效',
    'DMCA' =>'DMCA',
    'Contact_Us' =>'聯繫',
    'Video_Downloader' =>'Video Downloader',
	'Enter_url' => '輸入視頻鏈接...',
    'Supported_Sites' =>'可用網站',
    'Supported_Sites_text' =>'我們力求提供最佳的客戶服務。
這個平台擁有最受歡迎的網站，可讓您輕鬆快捷地下載視頻.
	',
    'How_to_download' =>'如何下載',
    'loader_input' =>'處理中...',
    'error_url_input' =>'目前，該服務不可用，或URL已損壞.',
    'error_server_input' =>'服務器出現問題。 再試一次.',
    'text_1' =>'1.複製網址',
    'text_2' =>'複製您要下載的視頻的網址',
    'text_3' =>'2.粘貼網址',
    'text_4' =>'粘貼視頻網址，請稍等.',
    'text_5' =>'3.下載視頻',
    'text_6' =>'輕鬆快速地選擇並下載您喜歡的視頻',
    'Share_social' =>'分享',
    'd_videos' =>'影片',
    'd_audio' =>'音訊',
    'd_list' =>'清單',
    'Format_file' =>'格式',
    'Quality_file' =>'質量',
    'size_file' =>'尺寸',
    'Download' =>'去下載',
    'Features' =>'視頻下載器功能',
    'Terms_of_Use' =>'條款和條件',
    'Privacy_Palicy' =>'私隱政策',
    'first_name' =>'名字',
    'last_name' =>'姓氏',
    'email' =>'電子郵件',
    'message_con' =>'評論',
    'ok_Comentario' =>'評論已成功發送.',
    'Ups_Comentario' =>'哎呀！出事了。 請再試一遍。.',
    'submit' =>'發送',
    'please_wait' =>'請稍候',
    'sent' =>'已發送',
    'Try_again' =>'再試一次',
    'ERROR_SERVER_1' =>'在數據庫中找到的信息.',
    'ERROR_SERVER_2' =>'無效的網址.',
    'ERROR_SERVER_3' =>'可用網址.',
    'ERROR_SERVER_4' =>'找不到信息，請重試.',
    'ERROR_SERVER_5' =>'ok',
    'te_info_1' =>'視頻質量選項； 480、720、1080，高清和4K',
    'te_info_2' =>'還提供MP3和不同的音頻格式.',
    'te_info_3' =>'完全免費.',
    'te_info_4' =>'您還可以在所有社交網絡上分享最喜歡的內容.',
    'te_info_5' =>'您可以下載多種格式.',
    'te_info_6' =>'24/7可用。 隨時為您提供.',
    'Cookies_text' =>'我們使用自己的Cookie和第三方Cookie來準備統計信息，並通過與我們合作夥伴共享的瀏覽分析來向您顯示個性化廣告。.',
    'Cookies_ok' =>'我知道了',
	'More_media' =>'更多下載工具',
	'blog_home_text' => '開始',
	'blog_articles_text' => '開始',
	'Most_popular' => '最多見的',
	'load_more_post' => '顯示更多',
	'seconds' => ' 秒',
	'minutes' => ' 分鐘',
	'hours' => ' 小時',
	'days' => ' 天',
	'months' => ' 月數',
	'years' => ' 年份',
);

$name_lang 	= '中國';
$case_lang 	= 'zh';
$url_lang 	= 'chinese';
$img_lang 	= 'https://i.imgur.com/yX70U5C.png';
  	
?>

