<?php
$lang_text      = array(
    '500_desc' => 'Database error.',
    '500_title' => 'This page is not.',
    '404_desc' => 'This page is not.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'the information is not valid',
    'DMCA' =>'DMCA',
    'Contact_Us' =>'Contact',
    'Video_Downloader' =>'Video Downloader',
	'Enter_url' => 'Enter the video link...',
    'Supported_Sites' =>'Available sites',
    'Supported_Sites_text' =>'We seek to provide the best customer service.
This platform has the most popular sites to download your videos in a simple and fast way.
	',
    'How_to_download' =>'How to Download?',
    'loader_input' =>'Loader...',
    'error_url_input' =>'At this moment the service is not available, or the URL is broken.',
    'error_server_input' =>'At this moment the service is not available, or the URL is broken.',
    'text_1' =>'1.Copy URL',
    'text_2' =>'Copy the URL of the video you want to download',
    'text_3' =>'2.Paste the URL',
    'text_4' =>'Paste the video URL and wait a moment.',
    'text_5' =>'3.Download the video',
    'text_6' =>'Choose and download your favorite video easy and fast',
    'Share_social' =>'Share',
    'd_videos' =>'Videos',
    'd_audio' =>'Audio',
    'd_list' =>'List',
    'Format_file' =>'Format',
    'Quality_file' =>'Quality',
    'size_file' =>'Size',
    'Download' =>'Download',
    'Features' =>'Video Downloader Features',
    'Terms_of_Use' =>'Terms and Conditions',
    'Privacy_Palicy' =>'Privacy policies',
    'first_name' =>'Names',
    'last_name' =>'Surnames',
    'email' =>'E-mail',
    'message_con' =>'Commentary',
    'ok_Comentario' =>'Comment sent successfully.',
    'Ups_Comentario' =>'Oops, something went wrong. Please try again..',
    'submit' =>'Send',
    'please_wait' =>'please wait',
    'sent' =>'Sent',
    'Try_again' =>'Try again',
    'ERROR_SERVER_1' =>'Information found in the database.',
    'ERROR_SERVER_2' =>'Invalid url.',
    'ERROR_SERVER_3' =>'URL available.',
    'ERROR_SERVER_4' =>'Information not found please try again.',
    'ERROR_SERVER_5' =>'ok',
    'te_info_1' =>'Video quality option; 480, 720, 1080, HD and 4K',
    'te_info_2' =>'Also available in MP3 and different audio formats.',
    'te_info_3' =>'and all this completely, without cost.',
    'te_info_4' =>'You can also share on all your social networks what you like the most.',
    'te_info_5' =>'You can download in multiple formats.',
    'te_info_6' =>'Available 24/7. Always available for you.',
    'Cookies_text' =>'We use our own and third party cookies to prepare statistical information and show you personalized advertising through the analysis of your navigation that we share with our partners..',
    'Cookies_ok' =>'I get it',
	'More_media' =>'More Downloader Tools',
	'blog_home_text' => 'Home',
	'blog_articles_text' => 'Articles',
	'Most_popular' => 'The most seen',
	'load_more_post' => 'Show more',
	'seconds' => ' Seconds',
	'minutes' => ' Minutes',
	'hours' => ' Hours',
	'days' => ' Days',
	'months' => ' Months',
	'years' => ' Years',
);

$name_lang 	= 'English';
$case_lang 	= 'en';
$url_lang 	= 'english';
$img_lang 	= 'https://i.imgur.com/cWawBzY.png';
  	
?>

