<?php
$lang_text      = array(
    '500_desc' => 'Erreur de la base de données.',
    '500_title' => 'Cette page n&#39;est pas.',
    '404_desc' => 'Cette page n&#39;est pas.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'l&#39;information n&#39;est pas valide',
    'DMCA' =>'DMCA',
    'Contact_Us' =>'Contact',
    'Video_Downloader' =>'Video Downloader',
	'Enter_url' => 'Entrez le lien vidéo...',
    'Supported_Sites' =>'Sites disponibles',
    'Supported_Sites_text' =>'Nous cherchons à fournir le meilleur service client.
Cette plateforme possède les sites les plus populaires pour télécharger vos vidéos de manière simple et rapide.
	',
    'How_to_download' =>'Comment télécharger?',
    'loader_input' =>'En traitement...',
    'error_url_input' =>'Pour le moment, le service n&#39;est pas disponible ou l&#39;URL est cassée.',
    'error_server_input' =>'Il y a eu un problème avec le serveur. Réessayer.',
    'text_1' =>'1.Copier le lien',
    'text_2' =>'Copiez l&#39;URL de la vidéo que vous souhaitez télécharger',
    'text_3' =>'2.Collez l&#39;URL',
    'text_4' =>'Collez l&#39;URL de la vidéo et attendez un instant.',
    'text_5' =>'3.Téléchargez la vidéo',
    'text_6' =>'Choisissez et téléchargez votre vidéo préférée facilement et rapidement',
    'Share_social' =>'Partager',
    'd_videos' =>'Vidéos',
    'd_audio' =>'l&#39;audio',
    'd_list' =>'liste',
    'Format_file' =>'Format',
    'Quality_file' =>'Qualité',
    'size_file' =>'Taille',
    'Download' =>'Télécharger',
    'Features' =>'Fonctionnalités du téléchargeur vidéo',
    'Terms_of_Use' =>'Termes et conditions',
    'Privacy_Palicy' =>'Les politiques de confidentialité',
    'first_name' =>'Noms',
    'last_name' =>'Noms de famille',
    'email' =>'Courrier électronique',
    'message_con' =>'Commentaire',
    'ok_Comentario' =>'Commentaire envoyé avec succès.',
    'Ups_Comentario' =>'Oups, quelque chose s&#39;est mal passé. Veuillez réessayer..',
    'submit' =>'Envoyer',
    'please_wait' =>'s&#39;il te plaît attends',
    'sent' =>'Envoyé',
    'Try_again' =>'Tente à nouveau',
    'ERROR_SERVER_1' =>'Informations trouvées dans la base de données.',
    'ERROR_SERVER_2' =>'URL invalide.',
    'ERROR_SERVER_3' =>'URL disponible.',
    'ERROR_SERVER_4' =>'Informations non trouvées, veuillez réessayer.',
    'ERROR_SERVER_5' =>'ok',
    'te_info_1' =>'Option de qualité vidéo; 480, 720, 1080, HD et 4K',
    'te_info_2' =>'Également disponible en MP3 et différents formats audio.',
    'te_info_3' =>'et tout cela sans frais.',
    'te_info_4' =>'Vous pouvez également partager sur tous vos réseaux sociaux ce que vous aimez le plus.',
    'te_info_5' =>'Vous pouvez télécharger en plusieurs formats.',
    'te_info_6' =>'Disponible 24/7. Toujours disponible pour vous.',
    'Cookies_text' =>'Nous utilisons nos propres cookies et ceux de tiers pour préparer des informations statistiques et vous montrer des publicités personnalisées à travers l&#39;analyse de votre navigation que nous partageons avec nos partenaires..',
    'Cookies_ok' =>'j&#39;ai compris',
	'More_media' =>'Plus d&#39;outils de téléchargement',
	'blog_home_text' => 'Début',
	'blog_articles_text' => 'Des articles',
	'Most_popular' => 'Le plus vu',
	'load_more_post' => 'Montre plus',
	'seconds' => ' Secondes',
	'minutes' => ' Minutes',
	'hours' => ' Heures',
	'days' => ' Jours',
	'months' => ' Mois',
	'years' => ' Années',	
);

$name_lang 	= 'français';
$case_lang 	= 'fr';
$url_lang 	= 'french';
$img_lang 	= 'https://i.imgur.com/g8URijh.png';
  	
?>

