<?php
$lang_text      = array(
    '500_desc' => 'Datenbankfehler.',
    '500_title' => 'Diese Seite ist nicht.',
    '404_desc' => 'Diese Seite ist nicht.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'Die Informationen sind ungültig',
    'DMCA' =>'DMCA',
    'Contact_Us' =>'Kontakt',
    'Video_Downloader' =>'Video Downloader',
	'Enter_url' => 'Geben Sie den Videolink ein...',
    'Supported_Sites' =>'Verfügbare Websites',
    'Supported_Sites_text' =>'Wir bemühen uns um den besten Kundenservice.
Diese Plattform bietet die beliebtesten Websites, auf denen Sie Ihre Videos einfach und schnell herunterladen können.
	',
    'How_to_download' =>'Wie downloadet man das?',
    'loader_input' =>'wird bearbeitet...',
    'error_url_input' =>'Derzeit ist der Dienst nicht verfügbar oder die URL ist fehlerhaft.',
    'error_server_input' =>'Es gab ein Problem mit dem Server. Versuch es noch einmal.',
    'text_1' =>'1.URL kopieren',
    'text_2' =>'Kopieren Sie die URL des Videos, das Sie herunterladen möchten',
    'text_3' =>'2.Fügen Sie die URL ein',
    'text_4' =>'Fügen Sie die Video-URL ein und warten Sie einen Moment.',
    'text_5' =>'3.Laden Sie das Video herunter',
    'text_6' =>'Wählen Sie Ihr Lieblingsvideo einfach und schnell aus und laden Sie es herunter',
    'Share_social' =>'Teilen',
    'd_videos' =>'Videos',
    'd_audio' =>'Audio',
    'd_list' =>'Liste',
    'Format_file' =>'Format',
    'Quality_file' =>'Qualität',
    'size_file' =>'Größe',
    'Download' =>'Herunterladen',
    'Features' =>'Video-Downloader-Funktionen',
    'Terms_of_Use' =>'Geschäftsbedingungen',
    'Privacy_Palicy' =>'Datenschutzrichtlinien',
    'first_name' =>'Namen',
    'last_name' =>'Nachnamen',
    'email' =>'E-mail',
    'message_con' =>'Kommentar',
    'ok_Comentario' =>'Kommentar erfolgreich gesendet.',
    'Ups_Comentario' =>'Ups! Irgendwas lief schief. Bitte versuche es erneut..',
    'submit' =>'Senden',
    'please_wait' =>'Warten Sie mal',
    'sent' =>'Geschickt',
    'Try_again' =>'Versuch es noch einmal',
    'ERROR_SERVER_1' =>'Informationen in der Datenbank gefunden.',
    'ERROR_SERVER_2' =>'Ungültige URL.',
    'ERROR_SERVER_3' =>'URL verfügbar.',
    'ERROR_SERVER_4' =>'Informationen nicht gefunden, versuchen Sie es erneut.',
    'ERROR_SERVER_5' =>'ok',
    'te_info_1' =>'Videoqualitätsoption; 480, 720, 1080, HD und 4K',
    'te_info_2' =>'Auch in MP3 und verschiedenen Audioformaten erhältlich.',
    'te_info_3' =>'und das alles völlig kostenlos.',
    'te_info_4' =>'Sie können auch in all Ihren sozialen Netzwerken teilen, was Ihnen am besten gefällt.',
    'te_info_5' =>'Sie können in mehreren Formaten herunterladen.',
    'te_info_6' =>'24/7 verfügbar. Immer für Sie verfügbar.',
    'Cookies_text' =>'Wir verwenden unsere eigenen Cookies und Cookies von Drittanbietern, um statistische Informationen zu erstellen und Ihnen personalisierte Werbung durch die Analyse Ihres Browsings zu zeigen, die wir mit unseren Partnern teilen.',
    'Cookies_ok' =>'Ich verstehe es',
	'More_media' =>'Weitere Downloader-Tools',
	'blog_home_text' => 'Anfang',
	'blog_articles_text' => 'Artikel',
	'Most_popular' => 'Am meisten gesehen',
	'load_more_post' => 'Zeig mehr',
	'seconds' => ' Sekunden',
	'minutes' => ' Protokoll',
	'hours' => ' Std',
	'days' => ' Tage',
	'months' => ' Monate',
	'years' => ' Jahre',	
);

$name_lang 	= 'deutsch';
$case_lang 	= 'de';
$url_lang 	= 'german';
$img_lang 	= 'https://i.imgur.com/fwaPN7g.png';
  	
?>

