<?php
$lang_text      = array(
    '500_desc' => 'Errore di Database.',
    '500_title' => 'Questa pagina non lo è.',
    '404_desc' => 'Questa pagina non lo è.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'l&#39;informazione non è valida',
    'DMCA' =>'DMCA',
    'Contact_Us' =>'Contatto',
    'Video_Downloader' =>'Video Downloader',
	'Enter_url' => 'Inserisci il collegamento video...',
    'Supported_Sites' =>'Siti disponibili',
    'Supported_Sites_text' =>'Cerchiamo di fornire il miglior servizio clienti.
Questa piattaforma ha i siti più popolari per scaricare i tuoi video in modo semplice e veloce.
	',
    'How_to_download' =>'Come scaricare?',
    'loader_input' =>'in lavorazione...',
    'error_url_input' =>'Al momento il servizio non è disponibile o l&#39;URL è rotto.',
    'error_server_input' =>'Si è verificato un problema con il server. Riprova.',
    'text_1' =>'1.Copia URL',
    'text_2' =>'Copia l&#39;URL del video che desideri scaricare',
    'text_3' =>'2.Incolla l&#39;URL',
    'text_4' =>'Incolla l&#39;URL del video e attendi un momento.',
    'text_5' =>'3.Scarica il video',
    'text_6' =>'Scegli e scarica il tuo video preferito in modo facile e veloce',
    'Share_social' =>'Condividere',
    'd_videos' =>'Video',
    'd_audio' =>'Audio',
    'd_list' =>'Elenco',
    'Format_file' =>'Formato',
    'Quality_file' =>'Qualità',
    'size_file' =>'Dimensione',
    'Download' =>'Scaricare',
    'Features' =>'Funzionalità di Downloader video',
    'Terms_of_Use' =>'Termini e condizioni',
    'Privacy_Palicy' =>'Politiche sulla privacy',
    'first_name' =>'Nomi',
    'last_name' =>'Cognomi',
    'email' =>'E-mail',
    'message_con' =>'Commento',
    'ok_Comentario' =>'Commento inviato con successo.',
    'Ups_Comentario' =>'Oops! Qualcosa è andato storto. Per favore riprova..',
    'submit' =>'Spedire',
    'please_wait' =>'attendere prego',
    'sent' =>'Inviato',
    'Try_again' =>'Riprova',
    'ERROR_SERVER_1' =>'Informazioni trovate nel database.',
    'ERROR_SERVER_2' =>'URL non valido.',
    'ERROR_SERVER_3' =>'URL disponibile.',
    'ERROR_SERVER_4' =>'Informazioni non trovate, si prega di riprovare.',
    'ERROR_SERVER_5' =>'ok',
    'te_info_1' =>'Opzione di qualità video; 480, 720, 1080, HD e 4K',
    'te_info_2' =>'Disponibile anche in MP3 e diversi formati audio.',
    'te_info_3' =>'e tutto questo completamente, senza costi.',
    'te_info_4' =>'Puoi anche condividere su tutti i tuoi social network ciò che ti piace di più.',
    'te_info_5' =>'Puoi scaricare in più formati.',
    'te_info_6' =>'Disponibile 24 ore su 24, 7 giorni su 7. Sempre disponibile per te.',
    'Cookies_text' =>'Utilizziamo cookie propri e di terze parti per preparare informazioni statistiche e mostrarti pubblicità personalizzata attraverso l&#39;analisi della tua navigazione che condividiamo con i nostri partner..',
    'Cookies_ok' =>'capisco',
	'More_media' =>'Altri strumenti di downloader',
	'blog_home_text' => 'Inizio',
	'blog_articles_text' => 'Articoli',
	'Most_popular' => 'Il più visto',
	'load_more_post' => 'Mostra di più',
	'seconds' => ' Secondi',
	'minutes' => ' Minuti',
	'hours' => ' Ore',
	'days' => ' Giorni',
	'months' => ' Mesi',
	'years' => ' Anni',
);

$name_lang 	= 'Italiano';
$case_lang 	= 'it';
$url_lang 	= 'italian';
$img_lang 	= 'https://i.imgur.com/omxxmye.png';
  	
?>

