<?php
$lang_text      = array(
    '500_desc' => 'Erro no banco de dados.',
    '500_title' => 'Esta página não é.',
    '404_desc' => 'Esta página não é.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'a informação não é válida',
    'DMCA' =>'DMCA',
    'Contact_Us' =>'Contato',
    'Video_Downloader' =>'Video Downloader',
	'Enter_url' => 'Digite o link do vídeo...',
    'Supported_Sites' =>'Sites disponíveis',
    'Supported_Sites_text' =>'Procuramos oferecer o melhor serviço ao cliente.
Essa plataforma possui os sites mais populares para baixar seus vídeos de maneira simples e rápida.
	',
    'How_to_download' =>'Como baixar',
    'loader_input' =>'Em processamento...',
    'error_url_input' =>'No momento, o serviço não está disponível ou o URL está quebrado.',
    'error_server_input' =>'Houve um problema com o servidor. Tente novamente.',
    'text_1' =>'1.URL da cópia',
    'text_2' =>'Copie o URL do vídeo que você deseja baixar',
    'text_3' =>'2.Cole o URL',
    'text_4' =>'Cole o URL do vídeo e aguarde um momento.',
    'text_5' =>'3.Faça o download do vídeo',
    'text_6' =>'Escolha e faça o download do seu vídeo favorito de forma fácil e rápida',
    'Share_social' =>'Compartilhar',
    'd_videos' =>'Vídeos',
    'd_audio' =>'Áudio',
    'd_list' =>'Lista',
    'Format_file' =>'Formato',
    'Quality_file' =>'Qualidade',
    'size_file' =>'Tamanho',
    'Download' =>'Baixar',
    'Features' =>'Recursos do Video Downloader',
    'Terms_of_Use' =>'Termos e Condições',
    'Privacy_Palicy' =>'Políticas de privacidade',
    'first_name' =>'Nomes',
    'last_name' =>'Sobrenomes',
    'email' =>'Correio eletrônico',
    'message_con' =>'Comentário',
    'ok_Comentario' =>'Comentário enviado com sucesso.',
    'Ups_Comentario' =>'Ops, algo deu errado. Por favor, tente novamente..',
    'submit' =>'Enviar',
    'please_wait' =>'por favor, espere',
    'sent' =>'Enviei',
    'Try_again' =>'Tenta de novo',
    'ERROR_SERVER_1' =>'Informações encontradas no banco de dados.',
    'ERROR_SERVER_2' =>'URL inválida.',
    'ERROR_SERVER_3' =>'URL disponível.',
    'ERROR_SERVER_4' =>'Informações não encontradas, tente novamente.',
    'ERROR_SERVER_5' =>'ok',
    'te_info_1' =>'Opção de qualidade de vídeo; 480, 720, 1080, HD e 4K',
    'te_info_2' =>'Também disponível em MP3 e diferentes formatos de áudio.',
    'te_info_3' =>'e tudo isso completamente, sem custo.',
    'te_info_4' =>'Você também pode compartilhar em todas as suas redes sociais o que mais gosta.',
    'te_info_5' =>'Você pode baixar em vários formatos.',
    'te_info_6' =>'Disponível 24/7. Sempre disponível para você.',
    'Cookies_text' =>'Utilizamos cookies próprios e de terceiros para preparar informações estatísticas e mostrar publicidade personalizada por meio da análise de sua navegação que compartilhamos com nossos parceiros.',
    'Cookies_ok' =>'entendi',
	'More_media' =>'Mais ferramentas do Downloader',
	'blog_home_text' => 'Começar',
	'blog_articles_text' => 'Artigos',
	'Most_popular' => 'O mais visto',
	'load_more_post' => 'Mostre mais',
	'seconds' => ' Segundos',
	'minutes' => ' Minutos',
	'hours' => ' Horas',
	'days' => ' Dias',
	'months' => ' Meses',
	'years' => ' Anos',	
);

$name_lang 	= 'Portugues';
$case_lang 	= 'pt';
$url_lang 	= 'portuguese';
$img_lang 	= 'https://i.imgur.com/F2xDxWq.png';
  	
?>

