<?php
$lang_text      = array(
    '500_desc' => 'Error con la Base de datos.',
    '500_title' => 'Esta página no está.',
    '404_desc' => 'Esta página no está.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'la información no es válida',
    'DMCA' =>'DMCA',
    'Contact_Us' =>'Contacto',
    'Video_Downloader' =>'Video Downloader',
	'Enter_url' => 'Ingrese el enlace del video...',
    'Supported_Sites' =>'Sitios disponibles',
    'Supported_Sites_text' =>'Buscamos brindar la mejor atencion al cliente.
		Esta plataforma cuenta con los sitios mas populares para poder descargar tus videos de una manera sencilla y rapida.
	',
    'How_to_download' =>'¿Cómo realizar la Descarga?',
    'loader_input' =>'Procesando...',
    'error_url_input' =>'En este momento el servicio no está disponible, o la URL se encuentra rota.',
    'error_server_input' =>'Hubo un problema con el servidor. Intente nuevamente.',
    'text_1' =>'1.Copiar URL',
    'text_2' =>'Copie la URL del video que desea descargar',
    'text_3' =>'2.Pegue la URL',
    'text_4' =>'Pegue la URL del video y espere un momento.',
    'text_5' =>'3.Descarga el video',
    'text_6' =>'Elige y descarga tu video favorito facil y rapido',
    'Share_social' =>'Compartir',
    'd_videos' =>'Videos',
    'd_audio' =>'Audio',
    'd_list' =>'Lista',
    'Format_file' =>'Formato',
    'Quality_file' =>'Calidad',
    'size_file' =>'Tamaño',
    'Download' =>'Descargar',
    'Features' =>'Características del descargador de video',
    'Terms_of_Use' =>'Términos y condiciones',
    'Privacy_Palicy' =>'Políticas de privacidad',
    'first_name' =>'Nombres',
    'last_name' =>'Apellidos',
    'email' =>'Correo electrónico',
    'message_con' =>'Comentario',
    'ok_Comentario' =>'Comentario enviado con éxito.',
    'Ups_Comentario' =>'Ups, algo ha salido mal. Favor de intentarlo de nuevo.',
    'submit' =>'Enviar',
    'please_wait' =>'por favor espera',
    'sent' =>'Enviado',
    'Try_again' =>'Intenta de nuevo',
    'ERROR_SERVER_1' =>'Información encontrada en la base de datos.',
    'ERROR_SERVER_2' =>'URL inválida.',
    'ERROR_SERVER_3' =>'URL no disponible.',
    'ERROR_SERVER_4' =>'Información no encontrada inténtelo de nuevo.',
    'ERROR_SERVER_5' =>'ok',
    'te_info_1' =>'Opcion de calidad de video; 480, 720, 1080, HD y 4K',
    'te_info_2' =>'Disponible también en MP3 y diferentes formatos de audio.',
    'te_info_3' =>'y Todo esto completamente, sin costo.',
    'te_info_4' =>'Tambien puedes compartir en todas tus redes sociales lo que más te gusta.',
    'te_info_5' =>'Puedes descargar en múltiples formatos.',
    'te_info_6' =>'Disponible 24/7. Siempre disponible para ti.',
    'Cookies_text' =>'Utilizamos Cookies propias y de terceros para elaborar información estadística y mostrarle publicidad 		personalizada a través del análisis de su navegación que compartimos con nuestros partners.',
    'Cookies_ok' =>'Entiendo',
	'More_media' =>'Más herramientas de descarga',
	'blog_home_text' => 'Inicio',
	'blog_articles_text' => 'Artículos',
	'Most_popular' => 'Lo mas visto',
	'load_more_post' => 'Mostrar más',
	'seconds' => ' Segundos',
	'minutes' => ' Minutos',
	'hours' => ' Horas',
	'days' => ' Dias',
	'months' => ' Meses',
	'years' => ' Años',
);

$name_lang 	= 'Español';
$case_lang 	= 'es';
$url_lang 	= 'spanish';
$img_lang 	= 'https://i.imgur.com/yVZWppU.png';
  	
?>

