<?php
$lang_text      = array(
    '500_desc' => 'Veri tabanı hatası.',
    '500_title' => 'Bu sayfa eksik.',
    '404_desc' => 'Bu sayfa eksik.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'bilgi geçerli değil',
    'DMCA' =>'DMCA',
    'Contact_Us' =>'İletişim',
    'Video_Downloader' =>'Video indirici',
	'Enter_url' => 'Video bağlantısını girin...',
    'Supported_Sites' =>'Kullanılabilir siteler',
    'Supported_Sites_text' =>'En iyi müşteri hizmetini sağlamaya çalışıyoruz.
Bu platform, videolarınızı basit ve hızlı bir şekilde indirmek için en popüler sitelere sahiptir.
	',
    'How_to_download' =>'Nasıl indirilir',
    'loader_input' =>'İşleme...',
    'error_url_input' =>'Şu anda hizmet kullanılamıyor veya URL bozuk.',
    'error_server_input' =>'Sunucuyla ilgili bir sorun oluştu. Tekrar deneyin.',
    'text_1' =>'1. URL&#39;yi kopyala',
    'text_2' =>'İndirmek istediğiniz videonun URL&#39;sini kopyalayın',
    'text_3' =>'2. URL&#39;yi yapıştırın',
    'text_4' =>'Video URL&#39;sini yapıştırın ve bir dakika bekleyin.',
    'text_5' =>'3. videoyu indirin',
    'text_6' =>'En sevdiğiniz videoyu kolay ve hızlı bir şekilde seçin ve indirin',
    'Share_social' =>'Paylaş',
    'd_videos' =>'Videolar',
    'd_audio' =>'Ses',
    'd_list' =>'Liste',
    'Format_file' =>'Biçim',
    'Quality_file' =>'Kalite',
    'size_file' =>'Boyut',
    'Download' =>'indirmek',
    'Features' =>'Video Downloader Özellikleri',
    'Terms_of_Use' =>'Şartlar ve koşullar',
    'Privacy_Palicy' =>'Gizlilik politikaları',
    'first_name' =>'İsimler',
    'last_name' =>'soyadları',
    'email' =>'E-posta',
    'message_con' =>'yorum',
    'ok_Comentario' =>'Yorum başarıyla gönderildi.',
    'Ups_Comentario' =>'Hoop! Birşeyler yanlış gitti. Lütfen tekrar deneyin..',
    'submit' =>'Gönder',
    'please_wait' =>'lütfen bekle',
    'sent' =>'Gönderilen',
    'Try_again' =>'Tekrar deneyin',
    'ERROR_SERVER_1' =>'Veritabanında bulunan bilgiler.',
    'ERROR_SERVER_2' =>'Geçersiz URL.',
    'ERROR_SERVER_3' =>'URL kullanılabilir.',
    'ERROR_SERVER_4' =>'Bilgi bulunamadı, lütfen tekrar deneyin.',
    'ERROR_SERVER_5' =>'ok',
    'te_info_1' =>'Video kalitesi seçeneği; 480, 720, 1080, HD ve 4K',
    'te_info_2' =>'MP3 ve farklı ses formatlarında da mevcuttur.',
    'te_info_3' =>'ve tüm bunlar tamamen, ücretsiz.',
    'te_info_4' =>'Ayrıca en sevdiğiniz şeyleri tüm sosyal ağlarınızda paylaşabilirsiniz.',
    'te_info_5' =>'Birden fazla formatta indirebilirsiniz.',
    'te_info_6' =>'24/7 kullanılabilir. Her zaman yanınızda.',
    'Cookies_text' =>'Kendi ve üçüncü taraf çerezlerimizi istatistiksel bilgiler hazırlamak ve ortaklarımızla paylaştığımız tarama analizinizle kişiselleştirilmiş reklamlar göstermek için kullanıyoruz..',
    'Cookies_ok' =>'anladım',
	'More_media' =>'Diğer İndirme Araçları',
	'blog_home_text' => 'Başlat',
	'blog_articles_text' => 'Nesne',
	'Most_popular' => 'En çok görülen',
	'load_more_post' => 'Daha fazla göster',
	'seconds' => ' Saniye',
	'minutes' => ' Dakika',
	'hours' => ' Saatler',
	'days' => ' Günler',
	'months' => ' Aylar',
	'years' => ' Yıllar',
);

$name_lang 	= 'Türk';
$case_lang 	= 'tr';
$url_lang 	= 'turkish';
$img_lang 	= 'https://i.imgur.com/hXssGnB.png';
  	
?>

